name: room_finder_flutter
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Base
  nb_utils: ^4.6.16
  google_fonts: ^2.1.0
  cached_network_image: ^3.1.0
  url_launcher: ^6.1.10
  intl: ^0.17.0


  # STATE MANAGEMENT
  mobx: ^2.0.3
  flutter_mobx: ^2.0.1
  cloud_firestore: ^4.4.3
  firebase_auth: ^4.2.9
  firebase_core: ^2.7.0
  firebase_storage: ^11.0.14
  equatable: ^2.0.5
  fluttertoast: ^8.2.1
  google_sign_in_web: ^0.11.0+1
  google_sign_in: ^6.0.1
  photo_view: ^0.14.0
  provider: ^6.0.5
  country_code_picker: ^2.0.2
  bloc: ^8.1.1
  get_it: ^7.2.0
  flutter_bloc: ^8.1.2
  image_picker: ^0.8.6+3
  firebase_messaging: ^14.2.5
  flutter_local_notifications: ^8.2.0
  json_annotation: ^4.8.0
  flutter_icons: ^1.1.0
  bubble: ^1.2.1
  percent_indicator: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  mobx_codegen: ^2.0.2
  build_runner: ^2.1.0
  json_serializable: ^6.6.1
  #flutter packages pub run build_runner build --delete-conflicting-outputs

flutter:

  uses-material-design: true

  assets:
    - images/roomFinding/
